version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started
      - grep -Fq "single" index.html
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed

# THIS IS THE MISSING PART THAT FIXES YOUR ERROR
artifacts:
  files:
    - '**/*'